### PR TITLE
Support Orleans 7.0.0

### PR DESCRIPTION
**Pull request by cecilphillip**
Changes
- Upgraded dependent NuGet packages
- Bumped version to 0.0.44-pre
- Removed ApplicationPartManagerExtensions
- Switch from IGrainActivationContext  to IGrainContext
- Updated samples

### CODE REVIEW

**Comment by cecilphillip** [comment]
@creyke Got time to take a look at this?

**Comment by creyke** [comment]
Yep will do today.

**Review by creyke — CHANGES_REQUESTED** [review]
This looks good, thank you for it.

There appears to be a large amount of spacing / EOL differences which are making it hard for me to diff confidently.

Is it possible (at least for SagaGrain.cs specifically) to only modify lines which require changes?

**Comment by cecilphillip** [comment]
@creyke I'm trying to figure out why it looks like that on GitHub but not in my local editor

**Pull request closed without merging**
